In [1]:
import pandas as pd

In [2]:
df_chart = pd.read_csv("CHARTEVENTS.csv", nrows=1000)

In [3]:
df_chart

,ROW_ID,SUBJECT_ID,HADM_ID,ICUSTAY_ID,ITEMID,CHARTTIME,STORETIME,CGID,VALUE,VALUENUM,VALUEUOM,WARNING,ERROR,RESULTSTATUS,STOPPED
0,788,36,165660,241249,223834,2134-05-12 12:00:00,2134-05-12 13:56:00,17525,15.00,15.00,L/min,0,0,NaN,NaN
1,789,36,165660,241249,223835,2134-05-12 12:00:00,2134-05-12 13:56:00,17525,100.00,100.00,NaN,0,0,NaN,NaN
2,790,36,165660,241249,224328,2134-05-12 12:00:00,2134-05-12 12:18:00,20823,0.37,0.37,NaN,0,0,NaN,NaN
3,791,36,165660,241249,224329,2134-05-12 12:00:00,2134-05-12 12:19:00,20823,6.00,6.00,min,0,0,NaN,NaN
4,792,36,165660,241249,224330,2134-05-12 12:00:00,2134-05-12 12:19:00,20823,2.50,2.50,NaN,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,863,36,165660,241249,224687,2134-05-12 16:00:00,2134-05-12 16:28:00,18428,11.00,11.00,L/min,0,0,NaN,NaN
996,864,36,165660,241249,224688,2134-05-12 16:00:00,2134-05-12 16:28:00,18428,20.00,20.00,insp/min,0,0,NaN,NaN
997,865,36,165660,241249,224689,2134-05-12 16:00:00,2134-05-12 16:28:00,18428,0.00,0.00,insp/min,0,0,NaN,NaN
998,866,36,165660,241249,224690,2134-05-12 16:00:00,2134-05-12 16:28:00,18428,20.00,20.00,insp/min,0,0,NaN,NaN
999,867,36,165660,241249,224695,2134-05-12 16:00:00,2134-05-12 16:28:00,18428,24.00,24.00,cmH2O,0,0,NaN,NaN

In [53]:
df_notes = pd.read_csv("NOTEEVENTS.csv")

/home/ubuntu/miniconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3442: DtypeWarning: Columns (4,5) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [69]:
df_notes["SUBJECT_ID"].nunique()

46146

In [68]:
for item in df_notes["CATEGORY"].unique():
    print(item, df_notes[df_notes["CATEGORY"]==item]["DESCRIPTION"].unique()[:10])
    print(".....")

Discharge summary ['Report' 'Addendum']
.....
Echo ['Report']
.....
ECG ['Report']
.....
Nursing ['Nursing Transfer Note' 'Nursing Progress Note' 'Nursing discharge note'
 'Generic Note' 'Addendum to transfer Note' 'progress note' 'set as error'
 'Nursing 1900-0700' 'Nursing Note' 'ICU Event Note']
.....
Physician  ['Physician Resident Progress Note' 'Physician Resident Admission Note'
 'Physician Attending Admission Note' 'Physician Attending Progress Note'
 'Arterial Line' 'Intensivist Note' 'Attending Progress Note'
 'Resident Progress Note' 'Transfer Planning' 'Family Meeting Note']
.....
Rehab Services ['Physical Therapy Evaluation Note' 'PT/Rehab Services' 'PT/Rehab'
 'Physical Therapy Progress Note' 'Generic Note' 'Rehab/PT' 'Contact note'
 'Physical Therapy Re-evaluation Note' 'Physical Therapy Contact Note'
 'PT Contact Note']
.....
Case Management  ['Case Management Continued Stay Review'
 'Case Managment Initial Patient Assessment'
 'Case Management Dicharge Plan' 'Nursing 1900-  0700'
 'Case Management Discharge Plan' 'Discharge Planning Note'
 'Discharge Plan - Update' 'Family Meeting Note' 'Discharge Note'
 'Case Management - Discharge Planning']
.....
Respiratory  ['Respiratory Care Shift Note' 'Generic Note' 'Respiratory Care'
 'Respiratory' 'Respiratory note' 'Respiratory Note'
 'Non standard trach tube;problem list item' 'Respiratory Care Note'
 'general' 'RESPIRATORY CARE:']
.....
Nutrition ['Clinical Nutrition Note' 'Generic Note' 'Clinical Nutrition Assessment'
 'Clinical Nutrition Not']
.....
General ['ICU Event Note' 'Generic Note' 'Physical Therapy Contact Note'
 'Critical Care Staff Addendum' 'ICU Staff Addendum' 'Respiratory Care'
 'Family Meeting Note' '--error--' 'ICU Attending Note'
 'ICU Attending  Note']
.....
Social Work ['Social Work Progress Note' 'Social Work Admission Note' 'Social Work'
 'progress note' 'Generic Note' 'Inital' 'Progress Note' 'Social work'
 'Social Work Note']
.....
Pharmacy ['Pharmacy Care Note' 'Pharmacy Vancomycin' 'Pharmacy - Sedation'
 'Pharmacy - Sedation/Agitation' 'Pharmacy - Vanco in CRRT'
 'Pharmacy - Methadone' 'Sedation and NMBAs' 'Resident Progress Note'
 'Sedation' 'Precedex']
.....
Consult ['Generic Note' 'Physician Consult Progress Note'
 'Physician Initial Consult Note' 'Cardiology Consult'
 'Cardiology consult' 'Cardiology follow-up' 'EP Consult follow-up'
 'EP follow-up note' 'EP Consult Note' 'Electrophysiology Consultation']
.....
Radiology ['DISTINCT PROCEDURAL SERVICE' 'CHEST (PORTABLE AP)'
 'CT PELVIS W/CONTRAST' 'CT HEAD W/O CONTRAST' 'CHEST (PA & LAT)'
 'CT CHEST W/O CONTRAST' 'CT GUIDANCE DRAINAGE' 'CHEST (SINGLE VIEW)'
 'CT ABDOMEN W/O CONTRAST' 'CVL/PICC']
.....
Nursing/other ['Report']
.....

In [56]:
df_notes["CATEGORY"].unique()

array(['Discharge summary', 'Echo', 'ECG', 'Nursing', 'Physician ',
       'Rehab Services', 'Case Management ', 'Respiratory ', 'Nutrition',
       'General', 'Social Work', 'Pharmacy', 'Consult', 'Radiology',
       'Nursing/other'], dtype=object)

In [57]:
df_notes[df_notes["SUBJECT_ID"]==13702]

,ROW_ID,SUBJECT_ID,HADM_ID,CHARTDATE,CHARTTIME,STORETIME,CATEGORY,DESCRIPTION,CGID,ISERROR,TEXT
1,175,13702,107527.0,2118-06-14,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2118-6-2**] Discharg...
2,176,13702,167118.0,2119-05-25,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2119-5-4**] D...
3,177,13702,196489.0,2124-08-18,NaN,NaN,Discharge summary,Report,NaN,NaN,Admission Date: [**2124-7-21**] ...
60248,59797,13702,196489.0,2124-07-24,NaN,NaN,Echo,Report,NaN,NaN,PATIENT/TEST INFORMATION:\nIndication: Chronic...
101350,106349,13702,196489.0,2124-07-24,NaN,NaN,ECG,Report,NaN,NaN,The rhythm may be sinus tachycardia with an at...
...,...,...,...,...,...,...,...,...,...,...,...
1460545,1441194,13702,167118.0,2119-05-20,2119-05-20 05:07:00,2119-05-20 05:39:00,Nursing/other,Report,17474.0,NaN,D Neuro: pt alert responding appropriately to ...
1462866,1441196,13702,167118.0,2119-05-20,2119-05-20 15:23:00,2119-05-20 15:43:00,Nursing/other,Report,19689.0,NaN,Nursing Progress Note.\n\nRESP: Pt received on...
1463102,1441142,13702,167118.0,2119-05-07,2119-05-07 04:57:00,2119-05-07 05:25:00,Nursing/other,Report,15767.0,NaN,"NPN:\n\nNeuro: Alert and oriented to place, an..."
1463103,1441143,13702,167118.0,2119-05-07,2119-05-07 06:41:00,2119-05-07 06:46:00,Nursing/other,Report,14236.0,NaN,RESPIRATORY CARE:\n\nFollowing for bronchodila...
1463104,1441195,13702,167118.0,2119-05-20,2119-05-20 05:58:00,2119-05-20 06:00:00,Nursing/other,Report,20955.0,NaN,RESPIRATORY CARE NOTE\n\nPt remains trached an...

In [55]:
print(df_notes[df_notes["SUBJECT_ID"]==13702].iloc[0]["TEXT"])

Admission Date:  [**2118-6-2**]       Discharge Date:  [**2118-6-14**]

Date of Birth:                    Sex:  F

Service:  MICU and then to [**Doctor Last Name **] Medicine

HISTORY OF PRESENT ILLNESS:  This is an 81-year-old female
with a history of emphysema (not on home O2), who presents
with three days of shortness of breath thought by her primary
care doctor to be a COPD flare.  Two days prior to admission,
she was started on a prednisone taper and one day prior to
admission she required oxygen at home in order to maintain
oxygen saturation greater than 90%.  She has also been on
levofloxacin and nebulizers, and was not getting better, and
presented to the [**Hospital1 18**] Emergency Room.

In the [**Hospital3 **] Emergency Room, her oxygen saturation was
100% on CPAP.  She was not able to be weaned off of this
despite nebulizer treatment and Solu-Medrol 125 mg IV x2.

Review of systems is negative for the following:  Fevers,
chills, nausea, vomiting, night sweats, change in weight,
gastrointestinal complaints, neurologic changes, rashes,
palpitations, orthopnea.  Is positive for the following:
Chest pressure occasionally with shortness of breath with
exertion, some shortness of breath that is positionally
related, but is improved with nebulizer treatment.

PAST MEDICAL HISTORY:
1. COPD.  Last pulmonary function tests in [**2117-11-3**]
demonstrated a FVC of 52% of predicted, a FEV1 of 54% of
predicted, a MMF of 23% of predicted, and a FEV1:FVC ratio of
67% of predicted, that does not improve with bronchodilator
treatment.  The FVC, however, does significantly improve with
bronchodilator treatment consistent with her known reversible
air flow obstruction in addition to an underlying restrictive
ventilatory defect.  The patient has never been on home
oxygen prior to this recent episode.  She has never been on
steroid taper or been intubated in the past.
2. Lacunar CVA.  MRI of the head in [**2114-11-4**]
demonstrates "mild degree of multiple small foci of high T2
signal within the white matter of both cerebral hemispheres
as well as the pons, in the latter region predominantly to
the right of midline.  The abnormalities, while nonspecific
in etiology, are most likely secondary to chronic
microvascular infarction.  There is no mass, lesion, shift of
the normal midline strictures or hydrocephalus.  The major
vascular flow patterns are preserved.  There is moderate
right maxillary, moderate bilateral ethmoid, mild left
maxillary, minimal right sphenoid, and frontal sinus mucosal
thickening.  These abnormalities could represent an allergic
or some other type of inflammatory process.  Additionally
noted is a moderately enlarged subtotally empty sella
turcica".
3. Angina:  Most recent stress test was in [**2118-1-3**]
going for four minutes with a rate pressure product of
10,000, 64% of maximum predicted heart rate without evidence
of ischemic EKG changes or symptoms.  The imaging portion of
the study demonstrated no evidence of myocardial ischemia and
a calculated ejection fraction of 84%.  The patient denies
angina at rest and gets angina with walking a few blocks.
Are alleviated by sublingual nitroglycerin.
4. Hypothyroidism on Synthroid.
5. Depression on Lexapro.
6. Motor vehicle accident with head injury approximately 10
years ago.

MEDICATIONS ON ADMISSION:
1. Hydrochlorothiazide 25 q.d.
2. Prednisone 60 mg, 50 mg, 40 mg, 20 mg.
3. Levofloxacin 500 mg q.d.
4. Imdur 60 mg q.d.
5. Synthroid 75 mcg q.d.
6. Pulmicort nebulizer b.i.d.
7. Albuterol nebulizer q.4. prn.
8. Lexapro 10 mg q.d.
9. Protonix 40 mg q.d.
10. Aspirin 81 mg q.d.

ALLERGIES:  Norvasc leads to lightheadedness and headache.

FAMILY HISTORY:  Noncontributory.

SOCIAL HISTORY:  Lives with her husband, Dr. [**Known lastname 1809**] an
eminent Pediatric Neurologist at [**Hospital3 1810**].  The
patient is a prior smoker, but has not smoked in over 10
years.  She has no known alcohol use and she is a full code.

PHYSICAL EXAM AT TIME OF ADMISSION:  Blood pressure 142/76,
heart rate 100 and regular, respirations at 17-21, and 97%
axillary temperature.  She was saturating at 100% on CPAP
with dry mucous membranes.  An elderly female in no apparent
distress.  Pupils are equal, round, and reactive to light and
accommodation.  Extraocular movements are intact.  Oropharynx
difficult to assess due to CPAP machine.  No evidence of
jugular venous pressure, however, the strap from the CPAP
machine obscures the neck exam.  Cranial nerves II through
XII are grossly intact.  Neck is supple without
lymphadenopathy.  Heart exam:  Tachycardic, regular, obscured
by loud bilateral wheezing with increase in the expiratory
phase as well as profuse scattered rhonchi throughout the
lung fields.  Positive bowel sounds, soft, nontender,
nondistended, obese, no masses.  Mild edema of the lower
extremities without clubbing or cyanosis, no rashes.  There
is a right hand hematoma.  Strength is assessed as [**5-9**] in the
lower extremities, [**5-9**] in the upper extremities with a normal
mental status and cognition.

LABORATORY STUDIES:  White count 19, hematocrit 41, platelets
300.  Chem-7:  127, 3.6, 88, 29, 17, 0.6, 143.  Troponin was
negative.  CKs were negative times three.  Initial blood gas
showed a pH of 7.4, pO2 of 66, pCO2 of 54.

Chest x-ray demonstrates a moderate sized hiatal hernia,
segmental atelectasis, left lower lobe infiltrate versus
segmental atelectasis.

EKG shows normal sinus rhythm at 113 beats per minute, normal
axis, no evidence of ST-T wave changes.

BRIEF SUMMARY OF HOSPITAL COURSE:
1. COPD/dyspnea/pneumonia:  The patient was initially placed
on an aggressive steroid taper and admitted to the Medical
Intensive Care Unit due to her difficulty with oxygenation
despite CPAP machine.  She was also given nebulizer
treatments q.4h. as well as chest PT.  The nebulizers were
increased to q.1h. due to the fact that she continued to have
labored breathing.

Due to persistent respiratory failure and labored breathing,
the patient was intubated on [**2118-6-7**] in order to improve
oxygenation, ventilation, and ability to suction.  A
bronchoscopy was performed on [**2118-6-7**], which demonstrated
marked narrowing of the airways with expiration consistent
with tracheomalacia.

On [**2118-6-9**], two silicone stents were placed, one in the left
main stem (12 x 25 and one in the trachea 16 x 40) by Dr.
[**First Name (STitle) **] [**Name (STitle) **] under rigid bronchoscopy with general anesthesia.

On [**2118-6-11**], the patient was extubated to a cool mist shovel
mask and her oxygen was titrated down to 2 liters nasal
cannula at which time she was transferred to the medical
floor.  On the medical floor, the steroids were weaned to off
on [**2118-6-14**], and the patient was saturating at 97% on 2
liters, 92% on room air.

On [**2118-6-14**], the patient was seen again by the Interventional
Pulmonology service, who agreed that she looked much improved
and recommended that she go to pulmonary rehabilitation with
followup within six weeks' time status post placement of
stents in respiratory failure.

2. Cardiovascular:  The patient was ruled out for a MI.  She
did have another episode on the medical floor of chest pain,
which showed no evidence of EKG changes and negative
troponin, negative CKs x3.  She was continued on aspirin,
Imdur, and diltiazem for rate control per her outpatient
regimen.

3. Hypertension:  She was maintained on diltiazem and
hydrochlorothiazide with adequate blood pressure control and
normalization of electrolytes.

4. Hematuria:  The patient had intermittent hematuria likely
secondary to Foley placement.  The Foley catheter was
discontinued on [**2118-6-14**].  She had serial urinalyses, which
were all negative for signs of infection.

5. Hyperglycemia:  Patient was placed on insulin-sliding
scale due to hyperglycemia, which was steroid induced.  This
worked quite well and her glucose came back to normal levels
once the steroids were tapered to off.

6. Leukocytosis:  Patient did have a profound leukocytosis of
20 to 22 during much of her hospital course.  As the steroids
were tapered to off, her white blood cell count on [**2118-6-14**]
was 15,000.  It was felt that the leukocytosis was secondary
to both steroids as well as question of a left lower lobe
pneumonia.

7. For the left lower lobe pneumonia, the patient had
initially received a course of levofloxacin 500 p.o. q.d.
from [**2118-6-4**] to [**2118-6-10**].  This was restarted on [**2118-6-12**]
for an additional seven day course given the fact that she
still had the leukocytosis and still had marked rales at the
left lower lobe.

8. Hypothyroidism:  The patient was continued on outpatient
medical regimen.

9. Depression:  The patient was continued on Lexapro per
outpatient regimen.  It is recommended that she follow up
with a therapist as an outpatient due to the fact that she
did have a blunted affect throughout much of the hospital
course, and did appear clinically to be depressed.

10. Prophylaxis:  She was maintained on proton-pump inhibitor
with subQ Heparin.

11. Sore throat:  The patient did have a sore throat for much
of the hospital course post extubation.  This was treated
with Cepacol lozenges as well as KBL liquid (a solution
containing Kaopectate, Bismuth, and lidocaine) at bedtime.

12. Communication/code status:  The patient was full code
throughout her hospital course, and communication was
maintained with the patient and her husband.

13. Muscle weakness:  The patient did have profound muscle
weakness and was evaluated by Physical Therapy, and was found
to have impaired functional mobility, impaired
musculoskeletal performance, impaired gas exchange, impaired
endurance, impaired ventilation, and needed help with supine
to sit.  However, she was able to tolerate sitting in a chair
for approximately one hour.

On motor exam, her flexors and extensors of the lower
extremities were [**4-8**] at the knee, [**4-8**] at the ankle, [**4-8**] at
the elbows, and [**4-8**] hips.  It was felt that this weakness was
most likely due to a combination of steroid myopathy as well
as muscle atrophy secondary to deconditioning after a
prolonged hospital course.

14. Speech/swallow:  The patient had a Speech and Swallow
evaluation showing no evidence of dysphagia, no evidence of
vocal cord damage status post tracheal stent placement.

DISCHARGE CONDITION:  The patient was able to oxygenate on
room air at 93% at the time of discharge.  She was profoundly
weak, but was no longer tachycardic and had a normal blood
pressure.  Her respirations were much improved albeit with
transmitted upper airway sounds.

DISCHARGE STATUS:  The patient will be discharged to [**Hospital1 **]
for both pulmonary and physical rehabilitation.

DISCHARGE MEDICATIONS:
1. Levothyroxine 75 mcg p.o. q.d.
2. Citalopram 10 mg p.o. q.d.
3. Aspirin 81 mg p.o. q.d.
4. Fluticasone 110 mcg two puffs inhaled b.i.d.
5. Salmeterol Diskus one inhalation b.i.d.
6. Acetaminophen 325-650 mg p.o. q.4-6h. prn.
7. Ipratropium bromide MDI two puffs inhaled q.2h. prn.
8. Albuterol 1-2 puffs inhaled q.2h. prn.
9. Zolpidem tartrate 5 mg p.o. q.h.s. prn.
10. Isosorbide dinitrate 10 mg p.o. t.i.d.
11. Diltiazem 60 mg p.o. q.i.d.
12. Pantoprazole 40 mg p.o. q.24h.
13. Trazodone 25 mg p.o. q.h.s. prn.
14. SubQ Heparin 5000 units subcutaneous b.i.d. until such
time that the patient is able to get out of bed twice a day.
15. Cepacol lozenges q.2h. prn.
16. Levofloxacin 500 mg p.o. q.d. for a seven day course to
be completed on [**2118-6-21**].
17. Kaopectate/Benadryl/lidocaine 5 mL p.o. b.i.d. prn, not
to be given around mealtimes for concern of dysphagia induced
by lidocaine.
18. Lorazepam 0.5-2 mg IV q.6h. prn.

FOLLOW-UP PLANS:  The patient is recommended to followup with
Dr. [**First Name4 (NamePattern1) **] [**Last Name (NamePattern1) 1407**], [**Telephone/Fax (1) 1408**] within two weeks of leaving
of the hospital.  She is also recommended to followup with
the Interventional Pulmonary service for followup status post
stent placement.  She is also recommended to followup with a
neurologist if her muscle weakness does not improve within
one week on physical therapy with concern for steroid-induced
myopathy.

FINAL DIAGNOSES:
1. Tracheomalacia status post tracheal and left main stem
bronchial stent placement.
2. Hypertension.
3. Hypothyroidism.
4. Restrictive lung defect.
5. Depression.


                     DR.[**Last Name (STitle) **],[**First Name3 (LF) **] 12-207


Dictated By:[**Last Name (NamePattern1) 1811**]
MEDQUIST36

D:  [**2118-6-14**]  11:30
T:  [**2118-6-14**]  11:33
JOB#:  [**Job Number 1812**]

In [38]:
print(df_notes[df_notes["CATEGORY"]=="ECG"].iloc[0]["TEXT"])

Sinus tachycardia
Short PR interval
Possible anterior infarct - age undetermined
Left atrial abnormality
Inferior T wave changes are borderline
Repolarization changes may be partly due to rate
Low QRS voltages in limb leads
Since previous tracing of [**2103-7-27**], no significant change

In [39]:
df_notes["CATEGORY"].unique()

array(['Discharge summary', 'Echo', 'ECG'], dtype=object)

In [10]:
df_items = pd.read_csv("D_ITEMS.csv")

In [16]:
df_items[df_items["ITEMID"]==223835]

,ROW_ID,ITEMID,LABEL,ABBREVIATION,DBSOURCE,LINKSTO,CATEGORY,UNITNAME,PARAM_TYPE,CONCEPTID
12413,12804,223835,Inspired O2 Fraction,FiO2,metavision,chartevents,Respiratory,None,Numeric,NaN

In [21]:
df_diag = pd.read_csv("DIAGNOSES_ICD.csv")

In [22]:
df_diag

        ROW_ID  SUBJECT_ID  HADM_ID  SEQ_NUM ICD9_CODE
0         1297         109   172335      1.0     40301
1         1298         109   172335      2.0       486
2         1299         109   172335      3.0     58281
3         1300         109   172335      4.0      5855
4         1301         109   172335      5.0      4254
...        ...         ...      ...      ...       ...
651042  639798       97503   188195      2.0     20280
651043  639799       97503   188195      3.0     V5869
651044  639800       97503   188195      4.0     V1279
651045  639801       97503   188195      5.0      5275
651046  639802       97503   188195      6.0      5569

[651047 rows x 5 columns]